#!/bin/bash  p.s. Was this wanting me to put just rev was the script? 
echo '''We can program your personal and business facebook pages to automatically Post Daily interesting Comments and pictures for you''' | rev
