#!/usr/bin/env bash
#FIZZBUZZZZZ
for ((q = 1; q <= 100; q++)); do
    if ((q % 3 == 0)) && ((q % 5 == 0)); then
        echo "FizzBuzz"
    elif ((q % 3 == 0)); then
        echo "Fizz"
    elif ((q % 5 == 0)); then
        echo "Buzz"
    else
        echo "$q"
    fi
done
