#!/usr/bin/env bash
# Displaying specific fields from /etc/passwd using cut

while IFS=: read -r line; do
    
    	username=$(echo "$line" | cut -d: -f1)
    
    	uid=$(echo "$line" | cut -d: -f3)
    	
    	home_dir=$(echo "$line" | cut -d: -f6)
    
    echo -e "$username\n$uid\n$home_dir\n"

done < /etc/passwd
