#!/usr/bin/env bash
#while loop that grants luck
i=1
while [ $i -lt 10 ]; do
        
        if [ $i ==  4 ]; then
                echo "bad luck"
        elif [ $i == 7 ]; then
                echo "good luck"
        else
                echo "Best School";
        fi
((i++));
done 
