#!/usr/bin/env bash
#this script tells you specific info about a file.
cool="school"

if [ -e "$cool" ]; then
    echo "$cool file exists"

    if [ -f "$cool" ]; then
        echo "$cool is a regular file"

        if [ -s "$cool" ]; then
            echo "$cool file is not empty"
        else
            echo "$cool file is empty"
        fi
    else
        echo "$cool is not a regular file"
    fi
else
    echo "$cool file does not exist"
fi

